import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useRouter } from "next/router"


const Preview: NextPage = () => {
  const router = useRouter();
  const { pid } = router.query;

  return (
    <div className='max-w-6xl mx-auto'>
      <Head>
        <title>SEAL Code Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex justify-between items-center pt-20'>
        <Link href='../'>
          <a className="text-2xl text-white bg-[#2386C9] rounded-lg px-12 py-4 transition hover:translate-y-1">
            Back
          </a>
        </Link>
        
        <h1 className="text-4xl text-white">
          {pid && pid[1].split('-')[0]}
        </h1>
      </header>

      <main className='pt-10'>
        {
          pid && <embed src={`/uploads/${pid[0]}/${pid[1]}`} width={`100%`} height={'600'}/>
        }
      </main>

    </div>
  )
}

export default Preview