import type { NextPage} from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useRouter } from "next/router"
import { MouseEvent, useEffect, useState} from "react";
import {server} from '../../config/config'
import jwt from 'jsonwebtoken'


const Preview: NextPage = () => {
  const [tokenToVerify, setTokenToVerify] = useState<string | null>(null);
  const router = useRouter();
  const { FileId, tokenId } = router.query as { FileId: string, tokenId: string };


  useEffect(()=>{
    tokenId !== undefined && 
    jwt.verify(tokenId, 'secret', async (err, decoded) => {
      if(err) router.push('/404');
      console.log(decoded)
    });
  },[tokenId, tokenToVerify])

  const previewFile = ()=>{
    if(!FileId) return;

    if(FileId.split('.')[1] === 'jpg' || FileId.split('.')[1] === 'png' || FileId.split('.')[1] === 'jpeg')
      return <Image src={`/img/${FileId}`} width={'100%'} height={'100%'} alt={`${FileId.split('-')[0]}`} />
     else 
      return <iframe src={`../img/${FileId}`} width={`100%`} height={'680'}></iframe>
    
  }

  const handleCopyLink = async (e: MouseEvent<HTMLButtonElement>)=>{
    e.preventDefault();

    if(tokenToVerify) return;

    const token = await fetch(`${server}/api/share`, {
      method: 'POST',
      body: JSON.stringify({
        url: `${server}/preview/${FileId}`
      }),
      headers: {
        'Content-Type': 'application/json'
      }
    })

    const tokenData = await token.json();
    setTokenToVerify(tokenData)
    await navigator.clipboard.writeText(`${server}/shareableLink?FileId=${FileId}?tokenId=${tokenData}`);
    alert('Copied to clipboard')
  }





  return (
    <div className='max-w-6xl mx-auto'>
      <Head>
        <title>SEAL Code Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex justify-between items-center pt-20'>
        <Link href='../'>
          <a className="text-2xl text-white bg-[#2386C9] rounded-lg px-12 py-4 transition hover:translate-y-1">
            Back
          </a>
        </Link>
        <div className='flex items-center gap-10'>
          <h1 className="text-4xl text-white">
            {FileId && FileId.split('-')[0]}
          </h1>
          <button className="text-2xl text-white bg-text rounded-lg px-12 py-4 cursor-pointer" onClick={handleCopyLink}>
            Share
          </button>
        </div>
      </header>

      <main className='pt-10'>
        {previewFile()}
      </main>

    </div>
  )
}

export default Preview