import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import FileComponent from '../components/FileComponent'
import Form from '../components/Form'


const Home: NextPage = () => {
  return (
    <div className='max-w-6xl mx-auto'>
      <Head>
        <title>SEAL Code Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex justify-between items-center pt-20'>
        <h1 className="text-4xl text-white">
          Upload a file here please:
        </h1>
        <Form/>
      </header>

      <main className='grid grid-cols-3 pt-10'>
        <FileComponent/>
      </main>

    </div>
  )
}

export default Home
